// <auto-generated />
using System;
using AcmeSystem.Presentation.ClientWeb.Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AcmeSystem.Presentation.ClientWeb.Migrations.AcmeSystemDb
{
    [DbContext(typeof(AcmeSystemDbContext))]
    [Migration("20200420153528_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AcmeSystem.Business.Metier.Model.Adresse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Localite");

                    b.Property<string>("Npa");

                    b.Property<string>("Numero");

                    b.Property<string>("Rue");

                    b.HasKey("Id");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("AcmeSystem.Business.Metier.Model.Compte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom");

                    b.HasKey("Id");

                    b.ToTable("Comptes");
                });

            modelBuilder.Entity("AcmeSystem.Business.Metier.Model.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdresseId");

                    b.Property<int?>("CompteId");

                    b.Property<string>("Nom");

                    b.Property<string>("Prenom");

                    b.HasKey("Id");

                    b.HasIndex("AdresseId");

                    b.HasIndex("CompteId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("AcmeSystem.Business.Metier.Model.Contact", b =>
                {
                    b.HasOne("AcmeSystem.Business.Metier.Model.Adresse", "Adresse")
                        .WithMany()
                        .HasForeignKey("AdresseId");

                    b.HasOne("AcmeSystem.Business.Metier.Model.Compte", "Compte")
                        .WithMany()
                        .HasForeignKey("CompteId");
                });
#pragma warning restore 612, 618
        }
    }
}
